export const ACTION = {
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    ADD_TODO_FAIL:'ADD_TODO_FAIL',
    ADD_TODO: 'ADD_TODO',
    MODIFY_TODO_SUCCESS: 'MODIFY_TODO_SUCCESS',
    MODIFY_TODO_FAIL:'MODIFY_TODO_FAIL',
    MODIFY_TODO: 'MODIFY_TODO',
    DELETE_TODO_SUCCESS:'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAIL:'DELETE_TODO_FAIL',
    DELETE_TODO: 'DELETE_TODO',
    GET_ALL_TODO_SUCCESS:'GET_ALL_TODO_SUCCESS',
    GET_ALL_TODO_FAIL:'GET_ALL_TODO_FAIL',
    GET_ALL_TODO: 'GET_ALL_TODO'
}